name = "viceprint"
compatibility_date = "2026-08-04"
pages_build_output_dir = "dist"

[vars]
PUBLIC_PAYPAL_CLIENT_ID = "BAArDZEY09ZY1N7U8xYRiiMozFjbENa0SMQAue48HyPLr2ukbhvEZ24mvMnaKT-8QLzSAtPD1B24AOtPdA"
PAYPAL_CLIENT_ID = "BAArDZEY09ZY1N7U8xYRiiMozFjbENa0SMQAue48HyPLr2ukbhvEZ24mvMnaKT-8QLzSAtPD1B24AOtPdA"
BUSINESS_EMAIL = "digitalvalueLLC@proton.me"
PAYPAL_ENV = "live"

[[kv_namespaces]]
binding = "RESERVATIONS"
id = "f27f3a27e0464afe8489392ad7e35c92"

[[kv_namespaces]]
binding = "LEADS"
id = "d6e3f99ed7fc4c088183040179a03de7"
