name = "viceprint"
compatibility_date = "2026-08-04"
pages_build_output_dir = "dist"

[vars]
PUBLIC_PAYPAL_CLIENT_ID = "AYjUkFYPEc5VTYU-JeHnEfY1KI6Y-FRfZHIuk2SUasjn6NSg-IV9NPFh04JYBrR3I1MidR_2upMzMQYl"
PAYPAL_CLIENT_ID = "AYjUkFYPEc5VTYU-JeHnEfY1KI6Y-FRfZHIuk2SUasjn6NSg-IV9NPFh04JYBrR3I1MidR_2upMzMQYl"
BUSINESS_EMAIL = "onboarding@resend.dev"
PAYPAL_ENV = "sandbox"

[[kv_namespaces]]
binding = "RESERVATIONS"
id = "f27f3a27e0464afe8489392ad7e35c92"

[[kv_namespaces]]
binding = "LEADS"
id = "d6e3f99ed7fc4c088183040179a03de7"
